### PR TITLE
Translated `FareDodger.xml` into Czech & fixed mistakes in Czech `CarBomb.xml`, `OffensiveWeaponReported.xml`, `StolenItem.xml` and `HighRiskEscort.xml`

### PR DESCRIPTION
**Pull request by technyk**

### CODE REVIEW

**Comment by technyk** [comment]
Fixed some mistakes in `CarBomb.xml` made by Wigleg

**Comment by technyk** [comment]
Fixed some mistakes in  `HighRiskEscort.xml` made by Wigleg

**Comment by Charlie-686** [comment]
Hey! Is this ready to be merged?

**Comment by technyk** [comment]
> Hey! Is this ready to be merged?

Yup! There's more files to come but that will probably be done by tommorow as I'm quite busy today

**Pull request merged**
