### PR TITLE
Add new Japanese Translations

### PR DESCRIPTION
**Pull request by DekoKiyo**
> [!IMPORTANT]
> Please merge this after completing the translations.

> Translations Status
- [x] Callouts
  - [x] AircraftInDistress.xml
  - [x] CarBomb.xml
  - [x] CustomPursuit.xml
  - [x] DisorientatedIndividual.xml
  - [x] FareDodger.xml
  - [x] Kidnapping.xml
  - [x] LargeVehiclePursuit.xml
  - [x] OffensiveWeaponReported.xml
  - [x] PhotographyofPoliceStation.xml
  - [x] Protest.xml
  - [x] Solicitation.xml
  - [x] StolenItem.xml
  - [x] StolenPedalBike.xml
  - [ ] ~~SubwayDisturbance.xml~~
  - [x] VehicleOnSidewalk.xml
- [x] General
  - [x] General.xml
  - [x] PedDescriptions.xml

> Need for a fixed list (Retranslate everything by @DekoKiyo)
- [x] Callouts
  - [x] DisorientatedIndividual.xml
  - [x] LargeVehiclePursuit.xml
  - [x] PhotographyofPoliceStation.xml
  - [x] VehicleOnSidewalk.xml
- [x] General
  - [x] General.xml

### CODE REVIEW

**Comment by Charlie-686** [comment]
You're doing great  :D

**Comment by DekoKiyo** [comment]
I'm done!
I retranslated all the files, so there are only my translations, haha.
You can merge this or wait for all translation files available.

**Review by Charlie-686 — CHANGES_REQUESTED** [review]
This looks great! But check solicitation.xml...I think you missed a line:

`<NOTIFICATION><![CDATA[~y~Establish contact with the suspect.~w~]]></NOTIFICATION>`

**Comment by DekoKiyo** [comment]
oops sorry, I've fixed it.

**Pull request merged**
